name: Build Python EXE

on:
  push:
    branches:
      - main  # mainブランチにプッシュしたときに実行

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # 必要なPythonバージョンを指定

    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build EXE
      run: |
        pyinstaller --onefile main.py
      # 出力ファイルは `dist/main.exe` に生成されます

    - name: Upload EXE to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: python-exe
        path: dist/main.exe
